targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          - lib/**_provider.dart
      freezed:
        generate_for:
          - lib/**/models/**.dart
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          - lib/**/models/**.dart