import 'package:freezed_annotation/freezed_annotation.dart';

part 'reminder.freezed.dart'; // Generated by freezed
part 'reminder.g.dart'; // Generated by json_serializable

@freezed
abstract class Reminder with _$Reminder {
  @JsonSerializable(
    fieldRename: FieldRename.snake,
    explicitToJson: true, // Needed if nested enums require toJson
  )
  const factory Reminder({
    required int id,
    required DateTime createdAt,
    String? note,
    DateTime? dueDate,
    required bool isCompleted,
    required String userId,
    int? projectId,
    int? lotId,
    required String tenantId,
  }) = _Reminder;

  factory Reminder.fromJson(Map<String, dynamic> json) => _$ReminderFromJson(json);
}
